# Generated by Django 4.2.2 on 2023-07-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_comment="主键", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        blank=True,
                        db_comment="类型   1 菜品分类 2 套餐分类",
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="分类名称",
                        max_length=64,
                        unique=True,
                        verbose_name="分类名称",
                    ),
                ),
                ("sort", models.IntegerField(db_comment="顺序", verbose_name="顺序")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, db_comment="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "菜品分类",
                "verbose_name_plural": "菜品分类管理",
                "db_table": "category",
                "db_table_comment": "菜品及套餐分类",
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_comment="主键", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="菜品名称",
                        max_length=64,
                        unique=True,
                        verbose_name="菜品名称",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_comment="菜品价格",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="菜品价格",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_comment="商品码", max_length=64, verbose_name="商品码"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        db_comment="图片", upload_to="product/", verbose_name="图片"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_comment="描述信息", max_length=400, null=True
                    ),
                ),
                (
                    "status",
                    models.IntegerField(db_comment="0 停售 1 起售", verbose_name="售卖状态"),
                ),
                ("sort", models.IntegerField(db_comment="顺序", verbose_name="顺序")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, db_comment="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.category",
                        verbose_name="菜品分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜品",
                "verbose_name_plural": "菜品管理",
                "db_table": "dish",
                "db_table_comment": "菜品管理",
            },
        ),
        migrations.CreateModel(
            name="DishFlavor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_comment="主键", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="口味名称", max_length=64, verbose_name="口味名称"
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        blank=True,
                        db_comment="口味数据list",
                        null=True,
                        verbose_name="口味详情",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, db_comment="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        db_comment="菜品",
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.dish",
                        verbose_name="菜品",
                    ),
                ),
            ],
            options={
                "verbose_name": "口味",
                "verbose_name_plural": "口味管理",
                "db_table": "dish_flavor",
                "db_table_comment": "菜品口味关系表",
            },
        ),
    ]
