# Generated by Django 4.2.2 on 2023-07-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_id_alter_dish_id_alter_dishflavor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                db_comment="菜品价格", decimal_places=2, max_digits=10, verbose_name="菜品价格"
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="status",
            field=models.BooleanField(
                db_comment="0 停售 1 起售", default=True, verbose_name="是否上架"
            ),
        ),
    ]
