# Generated by Django 4.2.2 on 2023-08-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_dish_price_alter_dish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='sale',
            field=models.IntegerField(db_comment='销量', default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '菜品分类'), (2, '套餐分类')], db_comment='类型   1 菜品分类 2 套餐分类', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='status',
            field=models.IntegerField(choices=[(0, '停售'), (1, '启售')], db_comment='0 停售 1 起售', default=1, verbose_name='售卖状态'),
        ),
    ]
