# Generated by Django 4.2.2 on 2023-07-04 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_comment="主键", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_comment="姓名",
                        max_length=50,
                        null=True,
                        verbose_name="姓名",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_comment="手机号", max_length=100, verbose_name="手机号"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        db_comment="状态 0:禁用，1:正常",
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, db_comment="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户管理",
                "db_table": "user",
                "db_table_comment": "用户信息",
            },
        ),
        migrations.CreateModel(
            name="AddressBook",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        db_comment="主键", primary_key=True, serialize=False
                    ),
                ),
                (
                    "consignee",
                    models.CharField(
                        db_comment="收货人", max_length=50, verbose_name="收货人"
                    ),
                ),
                (
                    "sex",
                    models.IntegerField(db_comment="性别 0 女 1 男", verbose_name="性别"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_comment="手机号", max_length=11, verbose_name="手机号"
                    ),
                ),
                (
                    "province_code",
                    models.CharField(
                        blank=True, db_comment="省级区划编号", max_length=12, null=True
                    ),
                ),
                (
                    "province_name",
                    models.CharField(
                        blank=True, db_comment="省级名称", max_length=32, null=True
                    ),
                ),
                (
                    "city_code",
                    models.CharField(
                        blank=True, db_comment="市级区划编号", max_length=12, null=True
                    ),
                ),
                (
                    "city_name",
                    models.CharField(
                        blank=True, db_comment="市级名称", max_length=32, null=True
                    ),
                ),
                (
                    "district_code",
                    models.CharField(
                        blank=True, db_comment="区级区划编号", max_length=12, null=True
                    ),
                ),
                (
                    "district_name",
                    models.CharField(
                        blank=True, db_comment="区级名称", max_length=32, null=True
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        db_comment="详细地址",
                        max_length=200,
                        null=True,
                        verbose_name="详细地址",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        db_comment="标签",
                        max_length=100,
                        null=True,
                        verbose_name="标签",
                    ),
                ),
                (
                    "is_default",
                    models.IntegerField(
                        db_comment="默认 0 否 1是", default=0, verbose_name="是否默认"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, db_comment="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "地址",
                "verbose_name_plural": "地址管理",
                "db_table": "address_book",
                "db_table_comment": "地址管理",
            },
        ),
    ]
