# Generated by Django 4.2.2 on 2023-07-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_addressbook_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.BooleanField(blank=True, default=True, verbose_name="状态"),
        ),
    ]
