# Generated by Django 4.2.2 on 2023-07-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.BooleanField(blank=True, default=True, verbose_name="是否有效"),
        ),
    ]
