# Generated by Django 4.2.2 on 2023-08-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '禁用'), (1, '正常')], db_comment='状态 0:禁用，1:正常', null=True, verbose_name='状态'),
        ),
    ]
