# Generated by Django 4.2.2 on 2023-08-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderdetail_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': '明细', 'verbose_name_plural': '订单明细'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pay_method',
            field=models.IntegerField(choices=[(1, '微信'), (2, '支付宝')], db_comment='支付方式 1微信,2支付宝', default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, '待付款'), (2, '待派送'), (3, '已派送'), (4, '已完成'), (5, '已取消')], db_comment='订单状态 1待付款，2待派送，3已派送，4已完成，5已取消', verbose_name='订单状态'),
        ),
    ]
